[workspace]
authors = ["Anthony Hiscox <anthonyhiscox@gmail.com>"]
channels = ["conda-forge"]
name = "qrcode_generator"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
reportlab = ">=4.3.1,<5"
qrcode = ">=8.1,<9"
