[project]
name = "double-sided-qr-generator"
version = "0.1.0"
description = "A tool for generating double-sided QR code sheets"
authors = []
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
python = ">=3.8"
qrcode = ">=7.4.2"
reportlab = ">=4.0.4"
pillow = ">=10.0.0"
coolname = ">=2.0.0"

[tasks]
generate = "python generate.py"
